(include_subdirs unqualified)

(tests
 (names
  ExpressionParserTest
  UtilTest
  CliUtilTest
  CliParserTest
  KyokaiSourceFileTest
  KyokaiSourceTextTest
  KyokaiLexicalTokenTest
  KyokaiSurfaceParserTest
  KyokaiInterfaceValidationTest
  KyokaiPackageSourceTest
  KyokaiPackageResolutionTest
  KyokaiPackageLockfileTest
  CRendererTest)
 (modules
  TestUtil
  ExpressionParserTest
  UtilTest
  CliUtilTest
  CliParserTest
  KyokaiSourceFileTest
  KyokaiSourceTextTest
  KyokaiLexicalTokenTest
  KyokaiSurfaceParserTest
  KyokaiInterfaceValidationTest
  KyokaiPackageSourceTest
  KyokaiPackageResolutionTest
  KyokaiPackageLockfileTest
  CRendererTest)
 (libraries austral_core ounit2))
