name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test-linux:
    strategy:
      fail-fast: true

    runs-on:
      - ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: nix cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: run linux bootstrap CI
        run: CI/linux-bootstrap.sh test

      - name: upload compiler binary
        uses: actions/upload-artifact@v4
        with:
          name: kyokai-linux-bootstrap-bin
          path: kyokai
          retention-days: 1

      - name: clean and verify output removal
        run: CI/linux-bootstrap.sh clean
