name: Build on MacOS
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on:
      - macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.0

      - name: build
        run: CI/macos-bootstrap.sh

      - name: upload compiler binary
        uses: actions/upload-artifact@v4
        with:
          name: kyokai-macos-bootstrap-bin
          path: kyokai
          retention-days: 1
